name: Playwright Test and Deploy to GitHub Pages

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'The directory where playwright tests are located'
        default: 'tests'
        required: false
        type: string
  push:
    branches:
      - gh-pages

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: yarn install

      - name: Install Playwright with Dependencies
        run: npx playwright install --with-deps
        
      - name: Run Playwright Tests
        run: yarn playwright test --reporter=html

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: playwright-traces-${{github.run_number}}-${{ github.run_attempt }}
          path: ${{ inputs.working-directory }}/playwright-report
          retention-days: 7
          if-no-files-found: ignore

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ !cancelled() }}
    steps:
      - name: Checkout GitHub Pages Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          persist-credentials: false

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Download Playwright Report
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: ${{ inputs.working-directory }}/playwright-report
      - name: Copy Playwright Report to Root
        run: |
          mkdir -p report
          cp -r ${{ inputs.working-directory }}/playwright-report/* ./report

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GB_TOKEN }}
        run: |
          git add .
          git commit -m "Update Playwright Test Report"
          git push origin gh-pages --force